### ISSUE TITLE
custom paint coordinate

### ISSUE THREAD

**Issue by toastyy00** [akasakaid/NotPixTod#1]
![image](https://github.com/user-attachments/assets/fb3f87be-696d-4242-aecd-782e7b848842)
 warnain gambar yg disediain pojok kanan atas, nanti dapet double PX

**Comment by bynodesx** [comment]
bang cara isi hexcode nya gimana ya? kok failed paint pixel id ya

**Comment by akasakaid** [comment]
> ![image](https://private-user-images.githubusercontent.com/108380151/372941801-fb3f87be-696d-4242-aecd-782e7b848842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjY1NDIsIm5iZiI6MTcyNzk2NjI0MiwicGF0aCI6Ii8xMDgzODAxNTEvMzcyOTQxODAxLWZiM2Y4N2JlLTY5NmQtNDI0Mi1hZWNkLTc4MmU3Yjg0ODg0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNDM3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzA0OWQwMzJhZWE1NWE5MzNlOGFiOTkxN2Q5ODkxODBkOWEyYjI5NTc2YjM1YmIxOWJmMTgyNjlmZGFlNjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.go_6GOydH311osNT9yOAhvlr6OFqAOx4bI-LkXN3PKM) warnain gambar yg disediain pojok kanan atas, nanti dapet double PX

Susah buat ngeimplementasiinnya. Mungkin kapan-kapan saya coba.

**Comment by ilcham0202** [comment]
> > ![image](https://private-user-images.githubusercontent.com/108380151/372941801-fb3f87be-696d-4242-aecd-782e7b848842.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NjY1NDIsIm5iZiI6MTcyNzk2NjI0MiwicGF0aCI6Ii8xMDgzODAxNTEvMzcyOTQxODAxLWZiM2Y4N2JlLTY5NmQtNDI0Mi1hZWNkLTc4MmU3Yjg0ODg0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxNDM3MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzA0OWQwMzJhZWE1NWE5MzNlOGFiOTkxN2Q5ODkxODBkOWEyYjI5NTc2YjM1YmIxOWJmMTgyNjlmZGFlNjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.go_6GOydH311osNT9yOAhvlr6OFqAOx4bI-LkXN3PKM) warnain gambar yg disediain pojok kanan atas, nanti dapet double PX
> 
> Susah buat ngeimplementasiinnya. Mungkin kapan-kapan saya coba.

bg coba lihat ini, pakai kordinate https://github.com/vadymfedorets/notpixel/tree/master/bot/points3x
