### ISSUE TITLE
failed get json response !

### ISSUE THREAD

**Issue by xNabil** [akasakaid/NotPixTod#10]
![IMG_20241011_151038_957](https://github.com/user-attachments/assets/72bd747d-df01-44da-9f75-eef26279260c)

any solutions?

**Comment by akasakaid** [comment]
> ![IMG_20241011_151038_957](https://github.com/user-attachments/assets/72bd747d-df01-44da-9f75-eef26279260c)
> 
> any solutions?

The solution is that you contact Not Pixel to upgrade the server.

**Comment by akasakaid** [comment]
> ![IMG_20241011_151038_957](https://github.com/user-attachments/assets/72bd747d-df01-44da-9f75-eef26279260c)
> 
> any solutions?

The solution is that you contact Not Pixel to upgrade the server.

**Comment by xNabil** [comment]
😂ok
