### ISSUE TITLE
[REQUEST] for random wait

### ISSUE THREAD

**Issue by geeks121** [akasakaid/NotPixTod#14]
random wait instead of fixed 1hours ,,, use random like 1 hours to 1.30 hours ,, so the bot choose 1.2 or 1.13 etc
also random seconds for repaint ,, instead using 1 seconds just randomly use 1 until 3

**Comment by xNabil** [comment]
I changed countdown 3 to 9 seconds in bot.py
now its working fine.


![Screenshot_20241012-061447](https://github.com/user-attachments/assets/22676a16-a829-4dc2-8b16-3cb6c0b12227)

**Comment by xNabil** [comment]
bro i did it myself 🙂,,this is my first time doing python 

now it wait's 9,20 seconds before painting 
2 paints and 1800-3600s before re run

now just need to fix the Painting Coordinates so we can get more rewards point

**Fawwaz Thoerif** bro please fix the coordinates 🥺🥺

in bot.py
![Screenshot_20241012-080205](https://github.com/user-attachments/assets/1d2d5f85-8197-45c2-a126-33429701d3fe)

in bot.py
![Screenshot_20241012-080043](https://github.com/user-attachments/assets/cb401651-31b5-4124-83f5-5420614983ca)

in the config json
![Screenshot_20241012-080627](https://github.com/user-attachments/assets/a4358203-f64a-4dbc-8b93-c8bb3c091b92)

**Comment by geeks121** [comment]
> bro i did it myself 🙂,,this is my first time doing python
> 
> now it wait's 9,20 seconds before painting 2 paints and 1800-3600s before re run
> 
> now just need to fix the Painting Coordinates so we can get more rewards point, **Fawwaz Thoerif** bro please fix the coordinates 🥺🥺
> 
> this is what i did in bot.py ![Screenshot_20241012-080205](https://private-user-images.githubusercontent.com/184257215/375916348-1d2d5f85-8197-45c2-a126-33429701d3fe.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDEwNjksIm5iZiI6MTcyODcwMDc2OSwicGF0aCI6Ii8xODQyNTcyMTUvMzc1OTE2MzQ4LTFkMmQ1Zjg1LTgxOTctNDVjMi1hMTI2LTMzNDI5NzAxZDNmZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMjM5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMzQwZDA0ZGEyNzViMTJkNGM1ODY5MjhiMDNiNjAxNTdhYTE1MmQ3ZmY4YTAyNWI5NWNmNDI1NmI1NmJmNGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.AN9aPd-t-c_rv_wE4dD9j9fwDTI4ECgq9_tHSdaP-qg)
> 
> in bot.py ![Screenshot_20241012-080043](https://private-user-images.githubusercontent.com/184257215/375916352-cb401651-31b5-4124-83f5-5420614983ca.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDEwNjksIm5iZiI6MTcyODcwMDc2OSwicGF0aCI6Ii8xODQyNTcyMTUvMzc1OTE2MzUyLWNiNDAxNjUxLTMxYjUtNDEyNC04M2Y1LTU0MjA2MTQ5ODNjYS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMjM5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mM2E3ZGQ1YjJlMDA0MzFjYzhiNTNhNTBiY2IyNWViOWQyNjFkZWY2OGU0ODA4MDg5M2U0MDcyZDExNWNmODVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MzvoTA-QfbWPmMWIllpdp-AXEJXyD3CeKgwEBCskvjc)
> 
> in the config json ![Screenshot_20241012-080627](https://private-user-images.githubusercontent.com/184257215/375916354-a4358203-f64a-4dbc-8b93-c8bb3c091b92.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg3MDEwNjksIm5iZiI6MTcyODcwMDc2OSwicGF0aCI6Ii8xODQyNTcyMTUvMzc1OTE2MzU0LWE0MzU4MjAzLWY2NGEtNGRiYy04YjkzLWM4YmIzYzA5MWI5Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMlQwMjM5MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMWIzM2I3NTlhMzU2NDk3NmNmODNiMTE5Mzg2NDU0ZGM1MzlhNzU1YjJmMjUyYmQ3NjBkZDdhYjg4MWEyYTdmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.yB8j4XUv47AmgsHCp9FLPtIrSSv53lSbWCEJix9V_hI)

for paiting i thing is to snipe the color,, example if biggest reward is blue ,,, then if there another color in it replace with blu ,, it's hard to implemented,,

**Comment by xNabil** [comment]
before the last NotPixel update 
the script cant detect wrong color so
the script used to color the Global painting wrong then fix it with the right paint 

after the last NotPixel bot update the painting's have changed,

***Fawwaz Thoerif*** bro please fix the coordinates and color like before 🥲

![Screenshot_20241009-133056](https://github.com/user-attachments/assets/e5c329a6-1355-4706-8eba-d9dfaad72a2b)
