### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Jax15161** [akasakaid/NotPixTod#2]
![Screenshot_2024-10-03-01-33-30-94_61c78dc80ee02b53007c815fefe993e3](https://github.com/user-attachments/assets/c3a5561e-5a93-4398-bf02-3fe0d4384ec6)

    return reader.tgread_object()
  File "/usr/local/lib/python3.10/dist-packages/telethon/extensions/binary
reader.py", line 131, in tgread_object
    return [self.tgread_object() for _ in range(self.read_int())]
  File "/usr/local/lib/python3.10/dist-packages/telethon/extensions/binary
reader.py", line 131, in <listcomp>
    return [self.tgread_object() for _ in range(self.read_int())]
  File "/usr/local/lib/python3.10/dist-packages/telethon/extensions/binary
reader.py", line 140, in tgread_object
    raise error
telethon.errors.common.TypeNotFoundError: Could not find a matching Constr
uctor ID for the TLObject that was supposed to be read with ID 83314fca. S
ee the FAQ for more details. Remaining bytes: b'\xcaO1\x83_\x04\x00\x02\x1
0\x00\x00\x00A<\x9cI\x01\x00\x00\x00Ck\x99\x1e\x89/\xb23\x06gffghh\x00\x08
\xf0\x9f\x8c\xb1SEED\x00\x00\x00\x07mnnnmop\r6283119351408\x00\x00?p\x8c\x
00%\x8c\xfdf\x82\xe0im\x81\x90\xd1\xe7\xe4\x92\xf6\xa2'
root@iZt4ngu6ailcz6wmep6uqtZ:~/NotPixTod#
[not] 0:bash*                      "iZt4ngu6ai

**Comment by akasakaid** [comment]
try to re run
