### ISSUE TITLE
Paint the pattern 

### ISSUE THREAD

**Issue by itazoomm** [akasakaid/NotPixTod#3]
![Screenshot_2024-10-03-11-05-33-57_948cd9899890cbd5c2798760b2b95377](https://github.com/user-attachments/assets/02fd355e-bb16-4565-8008-5550aa9e14f6)

If we complete the pattern determined by the game itself.  It will give three times more tokens.  Please add this option to the bot

**Comment by akasakaid** [comment]
It difficult sir.

**Comment by itazoomm** [comment]
Any updates?
