### ISSUE TITLE
account is flooded. skipping for now.

### ISSUE THREAD

**Issue by xNabil** [akasakaid/NotPixTod#9]
why this happens? and what is the solution?
![Screenshot_20241010-125807](https://github.com/user-attachments/assets/f7f48f52-9d7d-408a-896c-7f2a902a51bf)

**Comment by akasakaid** [comment]
IDK, that error is from telegram server.

**Comment by xNabil** [comment]
yeah, maybe thats the case,
i tried to increase the countdown and adding proxies but no dice

**Comment by geeks121** [comment]
i think best option is to add account using query ,,, has 2 option ,, login or query data.txt ,, its like major best bot till now

**Comment by xNabil** [comment]
how long a query lastes?

**Comment by akasakaid** [comment]
> i think best option is to add account using query ,,, has 2 option ,, login or query data.txt ,, its like major best bot till now

If the query data is durable I will not use this method.

**Comment by geeks121** [comment]
> how long a query lastes?

for majtod i use query 3 days ago and now still not changed or need to renew
